batch_size: 1
# iters: 40800
iters: 81600

train_dataset:
  type: OpticDiscSeg
  dataset_root: data/bookedge
  transforms:
#     - type: ResizeStepScaling
#       min_scale_factor: 0.75
#       max_scale_factor: 1.25
#       scale_step_size: 0.25
#     - type: RandomPaddingCrop
#       crop_size: [512, 512]
    - type: Resize
      target_size: [768, 768]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: OpticDiscSeg
  dataset_root: data/bookedge
  transforms:
    - type: Resize
      target_size: [640, 640]
    - type: Normalize
  mode: val

optimizer:
  type: AdamW
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.01

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.00006
  power: 1

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]

model:
  type: SegFormer_B5
  pretrained: https://bj.bcebos.com/paddleseg/dygraph/mix_vision_transformer_b5.tar.gz
#   pretrained: /data/jupyter/PaddleSeg/B0/iter_81600/model.pdparams


# batch_size: 1
# # iters: 40800
# iters: 81600

# train_dataset:
#   type: OpticDiscSeg
#   dataset_root: data/bookedge
#   transforms:
# #     - type: ResizeStepScaling
# #       min_scale_factor: 0.75
# #       max_scale_factor: 1.25
# #       scale_step_size: 0.25
# #     - type: RandomPaddingCrop
# #       crop_size: [512, 512]
#     - type: Resize
#       target_size: [640, 640]
#     - type: RandomHorizontalFlip
# #     - type: RandomDistort
# #       brightness_range: 0.4
# #       contrast_range: 0.4
# #       saturation_range: 0.4
#     - type: Normalize
#   mode: train

# val_dataset:
#   type: OpticDiscSeg
#   dataset_root: data/bookedge
#   transforms:
#     - type: Resize
#       target_size: [640, 640]
#     - type: Normalize
#   mode: val

# optimizer:
#   type: sgd

# lr_scheduler:
#   type: PolynomialDecay
#   learning_rate: 0.01
#   power: 0.9

# loss:
#   types:
#     - type: CrossEntropyLoss
#     - type: CrossEntropyLoss
#   coef: [1, 0.4]


# model:
#   backbone:
#   type: OCRNet
#   backbone:
#     type: HRNet_W48

#     pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w48_ssld.tar.gz
#   backbone_indices: [0]
