batch_size: 1
# iters: 40800
iters: 81600

train_dataset:
  type: OpticDiscSeg
  dataset_root: data/bookedge
  transforms:
    - type: ResizeRangeScaling
      min_value: 512
      max_value: 752
#     - type: RandomPaddingCrop
#       crop_size: [512, 512]
#     - type: Resize
#       target_size: [640, 640]
    - type: RandomHorizontalFlip
#     - type: RandomDistort
#       brightness_range: 0.4
#       contrast_range: 0.4
#       saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: OpticDiscSeg
  dataset_root: data/bookedge
  transforms:
    - type: Normalize
  mode: val

optimizer:
  type: AdamW
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.01

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.00006
  power: 1

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]

model:
  type: SegFormer_B5
  pretrained: https://bj.bcebos.com/paddleseg/dygraph/mix_vision_transformer_b5.tar.gz
#   pretrained: /data/jupyter/PaddleSeg/B0_768/iter_81600/model.pdparams